<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderProcessingMembersBL\OrderProcessingMembersBL.csproj" />
    <ProjectReference Include="..\OrderProcessingMembersDL\OrderProcessingMembersDL.csproj" />
  </ItemGroup>

</Project>
